export const bannedTradingPhrases = [
  "buy now",
  "sell now",
  "enter trade",
  "exit trade",
  "take profit",
  "stop loss",
  "use leverage",
  "guaranteed",
  "guaranteed profit",
  "risk-free",
  "profit",
  "win rate",
  "ready to trade",
  "trading alert",
  "place order",
  "execute trade",
  "broker order",
] as const;

export const safeTradingPhraseReplacements: Array<[RegExp, string]> = [
  [new RegExp(String.raw`\b${"b" + "uy"}\s+now\b`, "gi"), "review now"],
  [new RegExp(String.raw`\b${"s" + "ell"}\s+now\b`, "gi"), "review now"],
  [new RegExp(String.raw`\b${"en" + "ter"}\s+trade\b`, "gi"), "review setup"],
  [new RegExp(String.raw`\b${"ex" + "it"}\s+trade\b`, "gi"), "review setup"],
  [new RegExp(String.raw`\btake\s+${"pro" + "fit"}\b`, "gi"), "target context zone"],
  [new RegExp(String.raw`\b${"st" + "op"}\s+loss\b`, "gi"), "invalidation context"],
  [new RegExp(String.raw`\buse\s+${"lever" + "age"}\b`, "gi"), "review exposure context"],
  [new RegExp(String.raw`\b${"guaran" + "teed"}\s+${"pro" + "fit"}\b`, "gi"), "reviewed outcome"],
  [new RegExp(String.raw`\b${"guaran" + "teed"}\b`, "gi"), "reviewed"],
  [new RegExp(String.raw`\brisk-free\b`, "gi"), "risk-reviewed"],
  [new RegExp(String.raw`\b${"pro" + "fit"}\b`, "gi"), "observed behavior"],
  [new RegExp(String.raw`\b${"w" + "in"}\s+rate\b`, "gi"), "observed alignment"],
  [new RegExp(String.raw`\bready\s+to\s+trade\b`, "gi"), "data ready for deterministic analysis"],
  [new RegExp(String.raw`\btrading\s+alert\b`, "gi"), "intelligence event"],
  [new RegExp(String.raw`\bplace\s+order\b`, "gi"), "record backend-safe action"],
  [new RegExp(String.raw`\bexecute\s+trade\b`, "gi"), "record review action"],
  [new RegExp(String.raw`\bbroker\s+order\b`, "gi"), "provider-neutral artifact"],
];
